__title__ = 'waitress-raw'
__description__ = 'Raw HTTP Echo Server'
__url__ = 'https://github.com/realgam3/waitress-raw'
__version__ = '1.0.0'
__author__ = 'Tomer Zait (realgam3)'
__author_email__ = 'realgam3@gmail.com'
__license__ = 'Apache 2.0'
__copyright__ = 'Copyright 2020 Tomer Zait'
